config/routes.rb
Rails.application.routes.draw do  
  
  root to: 'peeps#index'
  devise_for :users
  resources :peeps

end

app/models/peep.rb
class Peep < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :peeps
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
    render text: 'Hello world'
  end
end

app/controllers/peeps_controller.rb
class PeepsController < ApplicationController
  def index
    @peeps = Peep.all
  end

  def new
    @peep = Peep.new
  end

  def create
    @peep = Peep.new peep_params
    if @peep.save
      redirect_to root_path
    end
  end

  private 

  def peep_params
    params.require(:peep).permit(:text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/peeps_helper.rb
module PeepsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
  <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to 'Sign up', new_user_registration_path %>
  <%= link_to 'Sign in', new_user_session_path %>
<% end %>

<%= yield %>

</body>
</html>

app/views/peeps/index.html.erb
<% if @peeps.any? %>
  <% @peeps.sort_by { |peep| peep.created_at }.reverse!.each do |peep| %>
    <%= peep.text %><br>
    <%= peep.created_at %><br>
  <% end %>
<% else %>
  No peeps peeped yet. Be the first!
<% end %>

<%= link_to 'Add a peep', new_peep_path %>

app/views/peeps/new.html.erb
<%= form_for @peep do |f| %>
  <%= f.label :text %>
  <%= f.text_field :text %>

  <%= f.submit 'Peep' %>
<% end %>